# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['waterRPA_lite.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=['hooks_lite'],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'cv2',
        'numpy',
        'numpy_distutils',
        'psutil',
        'tkinter',
        '_tkinter',
        'PIL.AvifImagePlugin',
        'PIL.FpxImagePlugin',
        'PIL.ImageTk',
        'PIL.MicImagePlugin',
        'PIL.PdfImagePlugin',
        'PIL.TiffImagePlugin',
        'PIL.WebPImagePlugin',
        'PySide6.QtNetwork',
        'PySide6.QtOpenGL',
        'PySide6.QtPdf',
        'PySide6.QtQml',
        'PySide6.QtQuick',
        'PySide6.QtSvg',
    ],
    noarchive=False,
    optimize=0,
)
def keep_lite_file(item):
    name = item[0].replace('\\', '/').lower()
    blocked = [
        'libcrypto',
        'libssl',
        'opengl32sw',
        'pyside6/qt6network',
        'pyside6/qtnetwork',
        'pyside6/qt6opengl',
        'pyside6/qtopengl',
        'pyside6/qt6pdf',
        'pyside6/qtpdf',
        'pyside6/qt6qml',
        'pyside6/qtqml',
        'pyside6/qt6quick',
        'pyside6/qtquick',
        'pyside6/qt6svg',
        'pyside6/qtsvg',
        'pyside6/qt6virtualkeyboard',
        'pyside6/plugins/iconengines/qsvgicon',
        'pyside6/plugins/imageformats/q',
        'pyside6/plugins/platforminputcontexts/qtvirtualkeyboard',
        'pyside6/plugins/platforms/qdirect2d',
        'pyside6/translations/',
        'pil/_avif',
        'pil/_imagingcms',
        'pil/_imagingft',
        'pil/_imagingmath',
        'pil/_imagingtk',
        'pil/_webp',
        '_tk_data',
        '_tcl_data',
        'tcl8',
        'tcl86',
        'tk86',
        'psutil',
    ]
    return not any(part in name for part in blocked)

a.binaries = [item for item in a.binaries if keep_lite_file(item)]
a.datas = [item for item in a.datas if keep_lite_file(item)]
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='waterRPA_lite_v1_5_single',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
