"""Product identity, compatibility baseline, and defensive resource limits."""

PRODUCT_NAME = "fukuaRPA"
APP_VERSION = "v1.0.11"
BUILD_NAME = "fukuaRPA_v1.0.11"
ONEFILE_BUILD_NAME = f"{BUILD_NAME}_single"
NATIVE_CORE_DLL_NAME = "fukua_rpa_core.dll"
SUPPORTED_WINDOWS_TEXT = "Windows 10 1809 及以上版本（仅 x64）和 Windows 11"

# Persistent data versions are independent from the marketing version.  Bump
# these only when a migration is added; never infer data compatibility from
# APP_VERSION.
PROFILE_SCHEMA_VERSION = 3
# Compatibility is bounded by the product major version. Raise this floor only
# in a major release after preserving/converting the previous user's data.
MIN_SUPPORTED_PROFILE_SCHEMA_VERSION = 0
PROFILE_BACKUP_VERSION = 2
DEFAULT_KEY_MAPPING_COUNT = 5
PROFILE_HISTORY_LIMIT = 12
PROFILE_HISTORY_MIN_INTERVAL_SECONDS = 60

TASK_TYPE_UNTIL = 15.0
TASK_TYPE_SET_VARIABLE = 16.0
TASK_TYPE_EXPRESSION = 17.0
TASK_TYPE_LAUNCH_APP = 18.0
TASK_TYPE_WAIT_WINDOW = 19.0
TASK_TYPE_ACTIVATE_WINDOW = 20.0
TASK_TYPE_CLOSE_WINDOW = 21.0
TASK_TYPE_SECRET_TEXT = 22.0
TASK_TYPE_UIA_CLICK = 23.0
TASK_TYPE_UIA_SET_VALUE = 24.0
TASK_TYPE_UIA_READ_VALUE = 25.0
UNTIL_CONDITION_MODES = ["图片出现", "图片消失", "区域发生变化", "区域变成指定图片"]
UNTIL_CONDITION_LOGICS = ["全部满足", "任一满足"]
UNTIL_LIMIT_ACTIONS = ["继续下一步", "停止脚本", "按失败处理"]

NATIVE_CORE_MIN_VERSION = 10400
NATIVE_CORE_MAX_VERSION = 19999
NATIVE_CORE_RELEASE_VERSION = 11200

MAX_PROFILES = 100
MAX_TASKS_PER_PROFILE = 5000
MAX_KEY_MAPPINGS = 256
MAX_PROFILE_NAME_LENGTH = 200
MAX_PROFILE_TOP_LEVEL_FIELDS = 256
MAX_TASK_FIELDS = 256
MAX_KEY_MAPPING_FIELDS = 64
MAX_PROFILE_JSON_BYTES = 64 * 1024 * 1024
MAX_SCALES_PER_TEMPLATE = 61
MAX_TEMPLATE_SOURCE_PIXELS = 25_000_000
MAX_TEMPLATE_CACHE_BYTES = 512 * 1024 * 1024
MAX_SINGLE_TEMPLATE_CACHE_BYTES = 128 * 1024 * 1024
MAX_CLICK_INDICATOR_OVERLAYS = 24
MAX_PACKAGE_FILES = 5000
MAX_PACKAGE_FILE_BYTES = 256 * 1024 * 1024
MAX_PACKAGE_TOTAL_BYTES = 1024 * 1024 * 1024

PROFILE_BACKUP_FORMAT = "fukuaRPA_profiles_backup"
LEGACY_PROFILE_BACKUP_FORMAT = "waterRPA_profiles_backup"
FULL_PACKAGE_FORMAT = "fukuaRPA_full_package"
LEGACY_FULL_PACKAGE_FORMAT = "waterRPA_full_package"
TASK_CLIPBOARD_KEY = "fukuaRPA_task"
LEGACY_TASK_CLIPBOARD_KEY = "waterRPA_task"
